  CREATE TABLE "LIDERES" 
   (	"ID_LIDER" NUMBER NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"TIPO_ASOCIADO" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER NOT NULL ENABLE, 
	"TIPO_USUARIO" VARCHAR2(300 BYTE) NOT NULL ENABLE,
	CONSTRAINT "LIDERES_PK" PRIMARY KEY ("ID_LIDER")
   );