REM INSERTING into USERS
SET DEFINE OFF;
-- contraseña: prueba
Insert into USERS (ID,PERSON_NAME,EMAIL,PASSWORD,IS_ADMIN,GUID,IS_PERFIL,IDFACEBOOK,IDTWITTER,SCREENNAME,NIF,FECHA_NACIMIENTO,FECHA_ALTA,ACTIVADO,IDTARJETACIUDADANA,EMPADRONADO,ANIO_NACIMIENTO,ID_DISTRITO,ID_SECCION,JUNTA,JUNTA_USER,MOBILE,IMAGE,ACEPTAMAIL,COD_PADRON,SEXO) values ('1992','prueba','prueba@prueba.es','{MD5}yJO61okntFfb7TlGDmr9Yg==','0','f60fffe3-e82d-2c15-983e-615bc79c28ca',null,null,null,null,'29115853S',null,to_date('13/12/16','DD/MM/RR'),'1',null,'Si','1988','4','63','Junta Casablanca',null,'612312342',null,null,null,null);
