CREATE TABLE "USERS"
(
  "ID"                 NUMBER(10, 0)      NOT NULL ENABLE,
  "PERSON_NAME"        VARCHAR2(256 BYTE) NOT NULL ENABLE,
  "EMAIL"              VARCHAR2(128 BYTE),
  "PASSWORD"           VARCHAR2(32 BYTE),
  "IS_ADMIN"           CHAR(1 BYTE),
  "GUID"               VARCHAR2(256 BYTE) NOT NULL ENABLE,
  "IS_PERFIL"          CHAR(1 BYTE),
  "IDFACEBOOK"         VARCHAR2(100 BYTE),
  "IDTWITTER"          NUMBER,
  "SCREENNAME"         VARCHAR2(200 BYTE),
  "NIF"                VARCHAR2(200 BYTE),
  "FECHA_NACIMIENTO"   DATE,
  "ACTIVADO"           NUMBER            DEFAULT 0,
  "FECHA_ALTA"         DATE,
  "IDTARJETACIUDADANA" VARCHAR2(100 BYTE),
  "EMPADRONADO"        VARCHAR2(20 BYTE),
  "ANIO_NACIMIENTO"    VARCHAR2(20 BYTE),
  "ID_DISTRITO"        NUMBER,
  "ID_SECCION"         NUMBER,
  "JUNTA"              VARCHAR2(200 BYTE),
  "JUNTA_USER"         VARCHAR2(200 BYTE),
  "MOBILE"             VARCHAR2(12 BYTE) DEFAULT NULL,
  "IMAGE"              VARCHAR2(60 BYTE),
  "ACEPTAMAIL"		   VARCHAR2(1 BYTE),
  "COD_PADRON"		   VARCHAR2(10 BYTE),
  "SEXO"			   VARCHAR2(1 BYTE),
  "DOCUMENTO_IDENTIFICATIVO" VARCHAR2(200 BYTE),
  CONSTRAINT "PK1" PRIMARY KEY ("ID")
);

CREATE SEQUENCE "SEQ_USERS" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 24803 NOCACHE NOORDER NOCYCLE;

CREATE TABLE "USERS_MOBILE_TOKEN"
(
  "ID"      NUMBER            NOT NULL ENABLE,
  "MOBILE"  VARCHAR2(12 BYTE) NOT NULL ENABLE,
  "TOKEN"   VARCHAR2(10 BYTE) NOT NULL ENABLE,
  "FECHA"   DATE DEFAULT sysdate,
  "USER_ID" NUMBER            NOT NULL ENABLE,
  "IP"      VARCHAR2(255 BYTE),
  "ACTIVE"  VARCHAR2(1 BYTE),
  CONSTRAINT "P_USR_TOKEN_MOBILE" PRIMARY KEY ("ID")
);

CREATE SEQUENCE "SEQ_USERS_MOBILE_TOKEN" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6781 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE "TEMPERATURA"
(
  "FECHA"  DATE,
  "MAXIMA" NUMBER,
  "MINIMA" NUMBER,
  "ICONO"  VARCHAR2(20 BYTE)
);